// Code generated by "stringer -type BuildTarget -linecomment -output build-target_string.go"; DO NOT EDIT.

package buildtarget

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RELEASE-1]
	_ = x[DEVELOP-2]
}

const _BuildTarget_name = "RELEASEDEVELOP"

var _BuildTarget_index = [...]uint8{0, 7, 14}

func (i BuildTarget) String() string {
	i -= 1
	if i >= BuildTarget(len(_BuildTarget_index)-1) {
		return "BuildTarget(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BuildTarget_name[_BuildTarget_index[i]:_BuildTarget_index[i+1]]
}
